version: '3.8'

services:
  hilan-automation:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./config:/app/config
      - ./screenshots:/app/screenshots
    restart: unless-stopped
    # For headless browser automation
    shm_size: '2gb'
    # Install Playwright browsers
    command: >
      sh -c "
        npx playwright install chromium &&
        node make-webhook.js
      "

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - hilan-automation
    restart: unless-stopped
    profiles:
      - production 